apiVersion: templates.krateo.io/v1alpha1
kind: aws-stack
metadata:
  name: aws-stack
spec:
  dashboard:
    description: demo stack
    icon: fa-brands fa-aws
    tags:
      - aws
      - stack
      - infrastructure
      - rds
    links:
      - url: https://github.com/maurosala/greedy-marmot
        title: maurosala/greedy-marmot
        icon: fa-brands fa-git
    plugins:
      - name: resources
        value: fat-squirrels
        type: argocd
        icon: fa-solid fa-diagram-project
      - name: documentation
        values:
          - README.md
          - sample.md
        type: doc
        icon: fa-solid fa-book-skull
      - name: pipelines
        values:
          - "[github.com] Build STABLE Docker image for every commit"
          - "[github.com] Build error"
          - "[github.com][maurosala][fat-squirrels] Publish Docker Images"
        type: pipeline
        icon: fa-solid fa-person-running
    owner: maurosala
  name: greedy-marmot
  compositionSelector:
    matchLabels:
      platform: aws
  eks:
    clusterName: greedy-clu
  network:
    networkName: greedy-net
  rds:
    rdsRegion: eu-central-1
    rdsDataDiskSizeGb: '10'
    rdsInstanceClass: db.t3.micro
    rdsEngineVersion: '13.4'
    rdsStorageType: standard
  fromRepo:
    domain: github.com
    provider: github
    apiUrl: https://api.github.com/
    repositoryName: krateo-template-aws-stack
    organizationName: krateoplatformops
    schema: https
  toRepo:
    domain: github.com
    provider: github
    apiUrl: https://api.github.com/
    repositoryName: greedy-marmot
    organizationName: maurosala
    schema: https
